### ISSUE TITLE
安卓分享图片报错

### ISSUE THREAD

**Issue by orzhtml** [little-snow-fox/react-native-wechat-lib#130]
FATAL EXCEPTION: main
    Process: com.gafc.rtls, PID: 16325
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at com.theweflex.react.WeChatModule.bitmapResizeGetBytes(WeChatModule.java:86)
        at com.theweflex.react.WeChatModule.access$000(WeChatModule.java:65)
        at com.theweflex.react.WeChatModule$1.invoke(WeChatModule.java:244)
        at com.theweflex.react.WeChatModule$7.onFailureImpl(WeChatModule.java:633)
        at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:60)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:180)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by orzhtml** [comment]
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-wechat-lib": "1.1.25-notpay",

调用的方法：shareImage

**Comment by little-snow-fox** [comment]
看起来是在调用图片压缩方法 image.compress 的时候出现空指针，但具体哪一个参数空了，我需要按照你的版本重起一个项目尝试才知道
