### ISSUE TITLE
打开android 就闪退，错误信息：RCTWeChat.registerApp got 2 arguments, expected 3

### ISSUE THREAD

**Issue by xclidongbo** [little-snow-fox/react-native-wechat-lib#227]
版本1.1.22
react native 0.63.2

```
2023-03-30 14:24:51.173 2813-3159/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.bridge.NativeArgumentsParseException: RCTWeChat.registerApp got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2023-03-30 14:24:51.173 2813-3159/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.bridge.NativeArgumentsParseException: RCTWeChat.registerApp got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
    
    
    --------- beginning of crash
2023-03-30 14:24:51.173 2813-3159/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.sinosig.meoa.app, PID: 2813
    com.facebook.react.bridge.NativeArgumentsParseException: RCTWeChat.registerApp got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)

```

**Comment by AudreyHepbur** [comment]
App.js

import * as WeChat from 'react-native-wechat-lib';
WeChat.registerApp('APPID', '');

**Comment by AudreyHepbur** [comment]
App.js

import * as WeChat from 'react-native-wechat-lib';
WeChat.registerApp('APPID', '');
