### ISSUE TITLE
Android 微信分享时报Uninitialized ActivityThread, likely app-created Instrumentation的异常

### ISSUE THREAD

**Issue by christtrc** [little-snow-fox/react-native-wechat-lib#32]
微信分享可以调起，在选择分享的用户时点击无反应。查看后台日志报：
```
2020-03-10 11:05:28.079 20294-20294/? E/Instrumentation: Uninitialized ActivityThread, likely app-created Instrumentation, disabling AppComponentFactory
    java.lang.Throwable
        at android.app.Instrumentation.getFactory(Instrumentation.java:1233)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1224)
        at com.tencent.mm.splash.k.newActivity(SourceFile:61)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

请问有什么解决办法？

**Comment by wong2** [comment]
> 微信分享可以调起，在选择分享的用户时点击无反应。

我遇到了同样的问题，查看官方文档后在 proguard 添加配置后好了：https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/Android.html
